export const data = [
    // {
    //   category: "men's clothing",
    //   description: "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    //   id: 1,
    //   image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    //   price: 109.95,
    //   rating: { rate: 3.9, count: 120 },
    //   title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    // },
    // {
    //   category: "men's clothing",
    //   description: "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    //   id: 2,
    //   image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    //   price: 22.3,
    //   rating: { rate: 4.1, count: 259 },
    //   title: "Mens Casual Premium Slim Fit T-Shirts ",
  
    // },
    // {
    //   category: "men's clothing",
    //   description: "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
    //   id: 3,
    //   image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    //   price: 55.99,
    //   rating: { rate: 4.7, count: 500 },
    //   title: "Mens Cotton Jacket",
    // },
    // {
    //   category: "men's clothing",
    //   description: "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
    //   id: 4,
    //   image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    //   price: 15.99,
    //   rating: { rate: 2.1, count: 430 },
    //   title: "Mens Casual Slim Fit",
    // },
    // {
    //   category: "jewelery",
    //   description: "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    //   id: 5,
    //   image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    //   price: 695,
    //   rating: { rate: 4.6, count: 400 },
    //   title: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    // },

    // {
    //   category: "electronics",
    //   description: "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    //   id: 6,
    //   image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    //   price: 999.99,
    //   rating: { rate: 2.2, count: 140 },
    //   title: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
    // },
    // {
    //   category: "women's clothing",
    //   description: "Season: Spring,Summer,Autumn,Winter.",
    //   id: 7,
    //   image: "/image/women1.jpg",
    //   price: 5.99,
    //   rating: { rate: 1.6, count: 149 },
    //   title: "Womens T Pants",
    // },
    // {
    //   category: "women's clothing",
    //   description: "Season: Spring,Summer,Autumn,Winter.",
    //   id: 8,
    //   image: "/image/women3.jpg",
    //   price: 5.99,
    //   rating: { rate: 18.6, count: 199 },
    //   title: "Womens T Pants",
    // },
    // {
    //   category: "men's clothing",
    //   description: "Your perfect pack for everyday use and walks in the forest and rain.",
    //   id: 9,
    //   image: "/image/shoe1.jpg",
    //   price: 5.99,
    //   rating: { rate: 40.6, count: 199 },
    //   title: "men slippers",
    // },
    {
      category: "jewelery",
      description: "Satisfaction Guaranteed. Return or exchange any order within 30 days.",
      id: 10,
      image: "/TrendingImage/ladies10.jpg",
      price: 50,
      rating: { rate: 38.6, count: 299 },
      title: "Solid Gold Petite Micropave ",
    },
  
  ]
  